owner: mutex-medical
repo: status

sites:
  - name: Application
    url: $STATUS_API_ENDPOINT
    method: POST
    headers:
      - "Content-Type: application/json"
      - "x-api-key: $STATUS_API_KEY"
    body: '{"type":"public","subdomain":"app"}'
    expectedStatusCodes:
      - 200

  - name: User API
    url: $STATUS_API_ENDPOINT
    method: POST
    headers:
      - "Content-Type: application/json"
      - "x-api-key: $STATUS_API_KEY"
    body: '{"type":"public","subdomain":"api"}'
    expectedStatusCodes:
      - 200

  - name: Agent API
    url: $STATUS_API_ENDPOINT
    method: POST
    headers:
      - "Content-Type: application/json"
      - "x-api-key: $STATUS_API_KEY"
    body: '{"type":"public","subdomain":"agent-api"}'
    expectedStatusCodes:
      - 200

  - name: Authentication
    url: $STATUS_API_ENDPOINT
    method: POST
    headers:
      - "Content-Type: application/json"
      - "x-api-key: $STATUS_API_KEY"
    body: '{"type":"public","subdomain":"auth"}'
    expectedStatusCodes:
      - 200

  - name: Storage
    url: $STATUS_API_ENDPOINT
    method: POST
    headers:
      - "Content-Type: application/json"
      - "x-api-key: $STATUS_API_KEY"
    body: '{"type":"public","subdomain":"storage"}'
    expectedStatusCodes:
      - 200

  - name: Documentation
    url: $STATUS_API_ENDPOINT
    method: POST
    headers:
      - "Content-Type: application/json"
      - "x-api-key: $STATUS_API_KEY"
    body: '{"type":"public","subdomain":"docs"}'
    expectedStatusCodes:
      - 200

  - name: Landing Page
    url: $STATUS_API_ENDPOINT
    method: POST
    headers:
      - "Content-Type: application/json"
      - "x-api-key: $STATUS_API_KEY"
    body: '{"type":"public","subdomain":"lp"}'
    expectedStatusCodes:
      - 200

  - name: "[Internal] Application"
    url: $STATUS_API_ENDPOINT
    method: POST
    headers:
      - "Content-Type: application/json"
      - "x-api-key: $STATUS_API_KEY"
    body: '{"type":"internal","subdomain":"app"}'
    expectedStatusCodes:
      - 200

  - name: "[Internal] API"
    url: $STATUS_API_ENDPOINT
    method: POST
    headers:
      - "Content-Type: application/json"
      - "x-api-key: $STATUS_API_KEY"
    body: '{"type":"internal","subdomain":"api"}'
    expectedStatusCodes:
      - 200

  - name: "[Internal] Agent API"
    url: $STATUS_API_ENDPOINT
    method: POST
    headers:
      - "Content-Type: application/json"
      - "x-api-key: $STATUS_API_KEY"
    body: '{"type":"internal","subdomain":"agent-api"}'
    expectedStatusCodes:
      - 200

  - name: "[Internal] Authentication"
    url: $STATUS_API_ENDPOINT
    method: POST
    headers:
      - "Content-Type: application/json"
      - "x-api-key: $STATUS_API_KEY"
    body: '{"type":"internal","subdomain":"auth"}'
    expectedStatusCodes:
      - 200

  - name: "[Internal] Storage"
    url: $STATUS_API_ENDPOINT
    method: POST
    headers:
      - "Content-Type: application/json"
      - "x-api-key: $STATUS_API_KEY"
    body: '{"type":"internal","subdomain":"storage"}'
    expectedStatusCodes:
      - 200

  - name: "[Internal] Documentation"
    url: $STATUS_API_ENDPOINT
    method: POST
    headers:
      - "Content-Type: application/json"
      - "x-api-key: $STATUS_API_KEY"
    body: '{"type":"internal","subdomain":"docs"}'
    expectedStatusCodes:
      - 200

status-website:
  cname: status.reze.app
  name: Reze Status
  introTitle: "**Reze** サービスステータス"
  introMessage: "Reze サービスのリアルタイムステータスページです。"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
